src/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Doctrine\ORM\Mapping\InheritanceType;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
#[InheritanceType('JOINED')]
#[DiscriminatorColumn(name: 'type', type: 'string')]
#[DiscriminatorMap(['user' => User::class, 'patient' => Patient::class])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    use TimestampableEntity;

    public const ICON = 'fas fa-user-gear';
    public const COLOR = 'primary';

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer', options: ['comment' => 'Unique identifier of the user'])]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true, options: ['comment' => 'Email of the user'])]
    #[Assert\NotBlank(message: 'Veuillez saisir votre adresse email.')]
    #[Assert\Email]
    private string $email;

    /**
     * @var array<string>
     */
    #[ORM\Column(type: 'json', options: ['comment' => 'Roles of the user'])]
    private array $roles = [];

    #[ORM\Column]
    private string $password;

    private ?string $plainPassword = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Veuillez saisir votre prénom.')]
    private ?string $firstName = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank(message: 'Veuillez saisir votre nom.')]
    private ?string $lastName = null;

    #[ORM\Column(type: 'boolean')]
    private bool $isVerified = false;

    #[ORM\Column(type: 'datetime', nullable: true, options: ['comment' => 'Last login time of the user'])]
    private ?\DateTimeInterface $lastLoginAt;

    public function __construct()
    {
        $this->lastLoginAt = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     * @return array<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param array<string> $roles
     *
     * @return $this
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function addRole(string $role): self
    {
        if (!$this->hasRole($role)) {
            $this->roles[] = $role;
        }

        return $this;
    }

    public function removeRole(string $role): self
    {
        if ($this->hasRole($role)) {
            $this->roles = array_diff($this->roles, [$role]);
        }

        return $this;
    }

    public function hasRole(string $role): bool
    {
        if (in_array($role, $this->getRoles(), true)) {
            return true;
        }

        return false;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        $this->plainPassword = null;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $password): self
    {
        $this->plainPassword = $password;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): static
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): static
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getIsVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getLastLoginAt(): ?\DateTimeInterface
    {
        return $this->lastLoginAt;
    }

    public function setLastLoginAt(?\DateTimeInterface $lastLoginAt): void
    {
        $this->lastLoginAt = $lastLoginAt;
    }

    public function getDisplayName(): string
    {
        return $this->firstName . ' ' . $this->lastName;
    }
}

templates/components/alert.html.twig
<div class="alert alert-{{ type }}">
{% if icon is not null %}
    <i class="fa {{ icon }}"></i>
{% endif %}
    {{ message|trans }}
</div>

templates/components/user-menu.html.twig
{# User Menu #}
{% set login = '#' %}
{% set logout = '#' %}
{% if loginRoute is not empty %}
    {% set login = path(loginRoute) %}
{% endif %}
{% if logoutRoute is not empty %}
    {% set logout = path(logoutRoute) %}
{% endif %}

{% if is_granted('IS_AUTHENTICATED_FULLY') %}
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="userMenu" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i> {{ app.user.displayName }}
        </a>
        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenu">
            {% if is_granted('ROLE_ADMIN') %}
                {% if actions is not empty %}
                    {% for action in actions %}
                        <li><a class="dropdown-item" href="{{ action.url }}"><i class="fas fa-{{ action.icon }}"></i> {{ action.label }}</a></li>
                    {% endfor %}
                    <li><hr class="dropdown-divider"></li>
                {% endif %}
            {% endif %}
            <li><a class="dropdown-item" href="{{ path('app_appointment_show', {'id': app.user.id }) }}"><i class="fa-solid fa-calendar"></i> Mes rendez-vous</a></li>
            <li><a class="dropdown-item" href="https://cathyassenheim.com/"><i class="fa-solid fa-rotate-left"></i> Visitez cathyassenheim.com</a></li>
            <li><a class="dropdown-item" href="{{ logout }}"><i class="fas fa-sign-out-alt"></i> Se déconnecter</a></li>
            <li>
                <a class="dropdown-item" href="{{ path('app_account') }}">
                    <span class="text-danger"><i class="fa-regular fa-trash-can"></i> Supprimer son compte</span>
                </a>
            </li>
        </ul>
    </li>
{% else %}
    <li class="nav-item">
        <a class="nav-link" href="{{ path('app_patient_register') }}"> S'inscrire</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{{ login }}"> Se connecter</a>
    </li>
{% endif %}